AdminPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.AdminPassword
AodhPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.AodhPassword
AodhDatabasePassword:
  role: Primary
  address: service_configs.aodh::db::mysql::password
CeilometerPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.CeilometerPassword
CeilometerMeteringSecret:
  file: overcloud-passwords.yaml
  address: parameter_defaults.CeilometerMeteringSecret
CinderPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.CinderPassword
CinderDatabasePassword:
  role: Primary
  address: service_configs.cinder::db::mysql::password
BarbicanPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.BarbicanPassword
BarbicanDatabasePassword:
  role: Primary
  address: service_configs.barbican::db::mysql::password
DatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.MysqlRootPassword
DbRootPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.MysqlRootPassword
DesignatePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.DesignatePassword
DesignateDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.DesignatePassword
GlancePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.GlancePassword
GlanceDatabasePassword:
  role: Primary
  address: service_configs.glance::db::mysql::password
HeatAuthEncriptionKey:
  file: overcloud-passwords.yaml
  address: parameter_defaults.HeatAuthEncryptionKey
HeatDatabasePassword:
  role: Primary
  address: service_configs.heat::db::mysql::password
IronicDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.IronicPassword
IronicInspectorDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.IronicPassword
IronicInspectorPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.IronicPassword
IronicPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.IronicPassword
ManilaPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.ManilaPassword
ManilaDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.ManilaPassword
MetadataSecret:
  file: overcloud-passwords.yaml
  address: parameter_defaults.AdminPassword
NeutronDatabasePassword:
  role: Primary
  address: service_configs.neutron::db::mysql::password
NovaApiDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.NovaPassword
NovaCell0DatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.NovaPassword
NovaCell1DatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.NovaPassword
NovaCell0MessageBussPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.NovaPassword
NovaPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.NovaPassword
OctaviaDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.OctaviaPassword
OctaviaPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.OctaviaPassword
PlacementDatabasePassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.PlacementPassword
PlacementPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.PlacementPassword
SwiftPassword:
  file: overcloud-passwords.yaml
  address: parameter_defaults.SwiftPassword

